AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler.handler
      Runtime: nodejs20.x
      CodeUri: ./dist
      MemorySize: 128
      Timeout: 5
      Policies: AWSLambdaBasicExecutionRole

